//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd, Version=1.1.4322.573 自动生成。
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1", IsNullable=false)]
public class Manifest {
    
    /// <remarks/>
    public Head Head;
    
    /// <remarks/>
    public ManifestDeclaration Declaration;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class Head {
    
    /// <remarks/>
    public string MessageID;
    
    /// <remarks/>
    public DeclarationFunctionCode FunctionCode;
    
    /// <remarks/>
    public DeclarationTypeCode1 MessageType;
    
    /// <remarks/>
    public string SenderID;
    
    /// <remarks/>
    public string ReceiverID;
    
    /// <remarks/>
    public HeadSendDateTime SendTime;
    
    /// <remarks/>
    public HeadVersionText Version;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Head")]
public class DeclarationFunctionCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public FunctionCode Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="FunctionCode")]
public enum FunctionCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class SealNumber {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AgencyCode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class TransportEquipmentFullnessCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class TransportEquipmentCharacteristicCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class EquipmentIdentification {
    
    /// <remarks/>
    public string ID;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class TransportEquipment {
    
    /// <remarks/>
    public EquipmentIdentification EquipmentIdentification;
    
    /// <remarks/>
    public TransportEquipmentCharacteristicCode CharacteristicCode;
    
    /// <remarks/>
    public TransportEquipmentFullnessCode FullnessCode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SealID")]
    public SealNumber[] SealID;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class AdditionalInformation {
    
    /// <remarks/>
    public string Reason;
    
    /// <remarks/>
    public string ContactName;
    
    /// <remarks/>
    public string ContactTel;
    
    /// <remarks/>
    public string Content;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class Commodity {
    
    /// <remarks/>
    public string CargoDescription;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class ConsignmentItemPackaging {
    
    /// <remarks/>
    public string MarksNumbers;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class ConsignmentItem {
    
    /// <remarks/>
    public string SequenceNumeric;
    
    /// <remarks/>
    public ConsignmentItemPackaging ConsignmentItemPackaging;
    
    /// <remarks/>
    public Commodity Commodity;
    
    /// <remarks/>
    public AdditionalInformation AdditionalInformation;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class PackagingTypeCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class ConsignmentPackaging {
    
    /// <remarks/>
    public System.Decimal QuantityQuantity;
    
    /// <remarks/>
    public PackagingTypeCode TypeCode;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class AssociatedTransportDocument {
    
    /// <remarks/>
    public string ID;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class TransportContractDocument {
    
    /// <remarks/>
    public string ID;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class Consignment {
    
    /// <remarks/>
    public TransportContractDocument TransportContractDocument;
    
    /// <remarks/>
    public AssociatedTransportDocument AssociatedTransportDocument;
    
    /// <remarks/>
    public ConsignmentPackaging ConsignmentPackaging;
    
    /// <remarks/>
    public System.Decimal TotalGrossMassMeasure;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalGrossMassMeasureSpecified;
    
    /// <remarks/>
    public ConsignmentItem ConsignmentItem;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class UnloadingLocationArrivalDate {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class UnloadingLocation {
    
    /// <remarks/>
    public string ID;
    
    /// <remarks/>
    public UnloadingLocationArrivalDate ArrivalDate;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class BorderTransportMeansTypeCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public TransportTypeCode Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="TransportTypeCode")]
public enum TransportTypeCode {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class BorderTransportMeans {
    
    /// <remarks/>
    public string JourneyID;
    
    /// <remarks/>
    public BorderTransportMeansTypeCode TypeCode;
    
    /// <remarks/>
    public string ID;
    
    /// <remarks/>
    public string Name;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Declaration")]
public class DeclarationDeclarationOfficeIdentifier {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManifestDeclaration))]
public class Declaration {
    
    /// <remarks/>
    public DeclarationDeclarationOfficeIdentifier DeclarationOfficeID;
    
    /// <remarks/>
    public BorderTransportMeans BorderTransportMeans;
    
    /// <remarks/>
    public UnloadingLocation UnloadingLocation;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Consignment")]
    public Consignment[] Consignment;
    
    /// <remarks/>
    public TransportEquipment TransportEquipment;
    
    /// <remarks/>
    public AdditionalInformation AdditionalInformation;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Declaration:datamodel:standard:CN:MT3201:1")]
public class ManifestDeclaration : Declaration {
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Head")]
public class HeadSendDateTime {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="DeclarationTypeCode", Namespace="Head")]
public class DeclarationTypeCode1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public DeclarationTypeCode Value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="DeclarationTypeCode")]
public enum DeclarationTypeCode {
    
    /// <remarks/>
    MT1101,
    
    /// <remarks/>
    MT1201,
    
    /// <remarks/>
    MT2101,
    
    /// <remarks/>
    MT2201,
    
    /// <remarks/>
    MT3101,
    
    /// <remarks/>
    MT3102,
    
    /// <remarks/>
    MT3201,
    
    /// <remarks/>
    MT3202,
    
    /// <remarks/>
    MT4101,
    
    /// <remarks/>
    MT4201,
    
    /// <remarks/>
    MT5101,
    
    /// <remarks/>
    MT5102,
    
    /// <remarks/>
    MT5201,
    
    /// <remarks/>
    MT5202,
    
    /// <remarks/>
    MT6101,
    
    /// <remarks/>
    MT6102,
    
    /// <remarks/>
    MT6201,
    
    /// <remarks/>
    MT6202,
    
    /// <remarks/>
    MT7101,
    
    /// <remarks/>
    MT8101,
    
    /// <remarks/>
    MT8102,
    
    /// <remarks/>
    MT8103,
    
    /// <remarks/>
    MT8104,
    
    /// <remarks/>
    MT8201,
    
    /// <remarks/>
    MT8202,
    
    /// <remarks/>
    MT8203,
    
    /// <remarks/>
    MT8204,
    
    /// <remarks/>
    MT9999,
    
    /// <remarks/>
    MTTE01,
    
    /// <remarks/>
    MTTE02,
    
    /// <remarks/>
    MTTE03,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="Head")]
public enum HeadVersionText {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.0")]
    Item10,
}
