<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2011r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:Declaration:datamodel:standard:CN:MT3101:1" exclude-result-prefixes="xs ns0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<Manifest>
			<xsl:for-each select="ns0:Manifest">
				<xsl:variable name="var1_Head" select="ns0:Head"/>
				<xsl:variable name="var2_Declaration" select="ns0:Declaration"/>
				<xsl:variable name="var3_BorderTransportMeans" select="$var2_Declaration/ns0:BorderTransportMeans"/>
				<xsl:variable name="var4_resultof_cast" select="string($var1_Head/ns0:MessageType)"/>
				<xsl:variable name="var5_resultof_substring" select="substring($var4_resultof_cast, number('4'), number('1'))"/>
				<xsl:variable name="var6_resultof_equal" select="($var4_resultof_cast = 'MT1101')"/>
				<xsl:variable name="var7_JourneyID" select="$var3_BorderTransportMeans/ns0:JourneyID"/>
				<xsl:variable name="var8_resultof_cast" select="string($var1_Head/ns0:MessageID)"/>
				<xsl:variable name="var9_resultof_cast" select="string($var1_Head/ns0:ReceiverID)"/>
				<xsl:variable name="var10_resultof_cast" select="string($var1_Head/ns0:SenderID)"/>
				<xsl:variable name="var11_resultof_cast" select="string($var3_BorderTransportMeans/ns0:ID)"/>
				<xsl:variable name="var12_resultof_cast" select="string($var7_JourneyID)"/>
				<xsl:variable name="var13_val">
					<xsl:choose>
						<xsl:when test="string(($var5_resultof_substring = '1')) != 'false'">
							<xsl:value-of select="'2'"/>
						</xsl:when>
						<xsl:when test="string(($var5_resultof_substring = '2')) != 'false'">
							<xsl:value-of select="'5'"/>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="'2'"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:variable>
				<msg_info>
					<msg_id>
						<xsl:value-of select="$var8_resultof_cast"/>
					</msg_id>
					<function_code>
						<xsl:value-of select="string($var1_Head/ns0:FunctionCode)"/>
					</function_code>
					<msg_type>
						<xsl:value-of select="substring-after($var4_resultof_cast, 'MT')"/>
					</msg_type>
					<sender_id>
						<xsl:value-of select="$var10_resultof_cast"/>
					</sender_id>
					<receiver_id>
						<xsl:value-of select="$var9_resultof_cast"/>
					</receiver_id>
					<send_time>
						<xsl:value-of select="string($var1_Head/ns0:SendTime)"/>
					</send_time>
					<version>
						<xsl:value-of select="string($var1_Head/ns0:Version)"/>
					</version>
				</msg_info>
				<content>
					<transport>
						<manifest_id>
							<xsl:choose>
								<xsl:when test="string((string($var13_val) = '2')) != 'false'">
									<xsl:value-of select="concat(concat($var11_resultof_cast, '_'), $var12_resultof_cast)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="string($var7_JourneyID)"/>
								</xsl:otherwise>
							</xsl:choose>
						</manifest_id>
						<arrival_no>
							<xsl:value-of select="$var8_resultof_cast"/>
						</arrival_no>
						<receiver_code>
							<xsl:value-of select="$var9_resultof_cast"/>
						</receiver_code>
						<sender_code>
							<xsl:value-of select="$var10_resultof_cast"/>
						</sender_code>
						<decl_traf_mode>
							<xsl:value-of select="string($var13_val)"/>
						</decl_traf_mode>
						<xsl:if test="string(((string($var6_resultof_equal) != 'false') or (($var4_resultof_cast = 'MT1201') or (($var4_resultof_cast = 'MT2101') or (($var4_resultof_cast = 'MT2201') or (($var4_resultof_cast = 'MT3101') or (($var4_resultof_cast = 'MT3102') or (($var4_resultof_cast = 'MT3201') or (($var4_resultof_cast = 'MT3202') or (($var4_resultof_cast = 'MT4101') or (($var4_resultof_cast = 'MT4201') or (($var4_resultof_cast = 'MT5101') or (($var4_resultof_cast = 'MT5102') or (($var4_resultof_cast = 'MT5201') or (($var4_resultof_cast = 'MT5202') or (($var4_resultof_cast = 'MT6101') or (($var4_resultof_cast = 'MT6102') or (($var4_resultof_cast = 'MT6201') or (($var4_resultof_cast = 'MT6202') or (($var4_resultof_cast = 'MT7101') or (($var4_resultof_cast = 'MT8101') or (($var4_resultof_cast = 'MT8102') or (($var4_resultof_cast = 'MT8103') or (($var4_resultof_cast = 'MT8104') or (($var4_resultof_cast = 'MT8201') or (($var4_resultof_cast = 'MT8202') or (($var4_resultof_cast = 'MT8203') or (($var4_resultof_cast = 'MT8204') or (($var4_resultof_cast = 'MTECEX') or ($var4_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
							<i_e_flag>
								<xsl:choose>
									<xsl:when test="string((string($var6_resultof_equal) != 'false')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT1201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT2101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT2201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT3101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT3102')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT3201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT3202')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT4101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT4201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT5101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT5102')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT5201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT5202')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT6101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT6102')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT6201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT6202')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT7101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8102')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8103')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8104')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8202')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8203')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MT8204')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var4_resultof_cast = 'MTECEX')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:if test="string(($var4_resultof_cast = 'MTECIM')) != 'false'">
											<xsl:value-of select="'I'"/>
										</xsl:if>
									</xsl:otherwise>
								</xsl:choose>
							</i_e_flag>
						</xsl:if>
						<voyage_no>
							<xsl:value-of select="$var12_resultof_cast"/>
						</voyage_no>
						<transport_id>
							<xsl:value-of select="$var11_resultof_cast"/>
						</transport_id>
						<customs_code>
							<xsl:value-of select="string($var2_Declaration/ns0:DeclarationOfficeID)"/>
						</customs_code>
						<xsl:for-each select="$var2_Declaration/ns0:AdditionalInformation">
							<remark>
								<xsl:value-of select="string(ns0:Content)"/>
							</remark>
						</xsl:for-each>
					</transport>
					<bills>
						<xsl:for-each select="$var2_Declaration/ns0:Consignment">
							<xsl:variable name="var14_AssociatedTransportDocument" select="ns0:AssociatedTransportDocument"/>
							<xsl:variable name="var15_resultof_exists" select="boolean($var14_AssociatedTransportDocument)"/>
							<bill>
								<manifest_id>
									<xsl:choose>
										<xsl:when test="string((string($var13_val) = '2')) != 'false'">
											<xsl:value-of select="concat(concat($var11_resultof_cast, '_'), $var12_resultof_cast)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string($var7_JourneyID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</manifest_id>
								<arrival_no>
									<xsl:value-of select="$var8_resultof_cast"/>
								</arrival_no>
								<bill_no>
									<xsl:choose>
										<xsl:when test="string((string($var15_resultof_exists) != 'false')) != 'false'">
											<xsl:for-each select="$var14_AssociatedTransportDocument">
												<xsl:value-of select="string(ns0:ID)"/>
											</xsl:for-each>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</bill_no>
								<bill_type>
									<xsl:choose>
										<xsl:when test="string((string($var15_resultof_exists) != 'false')) != 'false'">
											<xsl:value-of select="'1'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'0'"/>
										</xsl:otherwise>
									</xsl:choose>
								</bill_type>
								<xsl:if test="string((string($var15_resultof_exists) != 'false')) != 'false'">
									<parent_bill_no>
										<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
									</parent_bill_no>
								</xsl:if>
								<decl_traf_mode>
									<xsl:value-of select="string($var13_val)"/>
								</decl_traf_mode>
								<xsl:if test="string(((string($var6_resultof_equal) != 'false') or (($var4_resultof_cast = 'MT1201') or (($var4_resultof_cast = 'MT2101') or (($var4_resultof_cast = 'MT2201') or (($var4_resultof_cast = 'MT3101') or (($var4_resultof_cast = 'MT3102') or (($var4_resultof_cast = 'MT3201') or (($var4_resultof_cast = 'MT3202') or (($var4_resultof_cast = 'MT4101') or (($var4_resultof_cast = 'MT4201') or (($var4_resultof_cast = 'MT5101') or (($var4_resultof_cast = 'MT5102') or (($var4_resultof_cast = 'MT5201') or (($var4_resultof_cast = 'MT5202') or (($var4_resultof_cast = 'MT6101') or (($var4_resultof_cast = 'MT6102') or (($var4_resultof_cast = 'MT6201') or (($var4_resultof_cast = 'MT6202') or (($var4_resultof_cast = 'MT7101') or (($var4_resultof_cast = 'MT8101') or (($var4_resultof_cast = 'MT8102') or (($var4_resultof_cast = 'MT8103') or (($var4_resultof_cast = 'MT8104') or (($var4_resultof_cast = 'MT8201') or (($var4_resultof_cast = 'MT8202') or (($var4_resultof_cast = 'MT8203') or (($var4_resultof_cast = 'MT8204') or (($var4_resultof_cast = 'MTECEX') or ($var4_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
									<i_e_flag>
										<xsl:choose>
											<xsl:when test="string((string($var6_resultof_equal) != 'false')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT1201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT2101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT2201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT4101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT4201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT7101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8103')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8104')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8203')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8204')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MTECEX')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:if test="string(($var4_resultof_cast = 'MTECIM')) != 'false'">
													<xsl:value-of select="'I'"/>
												</xsl:if>
											</xsl:otherwise>
										</xsl:choose>
									</i_e_flag>
								</xsl:if>
								<customs_code>
									<xsl:value-of select="string($var2_Declaration/ns0:DeclarationOfficeID)"/>
								</customs_code>
							</bill>
						</xsl:for-each>
					</bills>
					<contas>
						<xsl:for-each select="$var2_Declaration/ns0:TransportEquipment">
							<conta>
								<manifest_id>
									<xsl:choose>
										<xsl:when test="string((string($var13_val) = '2')) != 'false'">
											<xsl:value-of select="concat(concat($var11_resultof_cast, '_'), $var12_resultof_cast)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string($var7_JourneyID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</manifest_id>
								<arrival_no>
									<xsl:value-of select="$var8_resultof_cast"/>
								</arrival_no>
								<decl_traf_mode>
									<xsl:value-of select="string($var13_val)"/>
								</decl_traf_mode>
								<xsl:if test="string(((string($var6_resultof_equal) != 'false') or (($var4_resultof_cast = 'MT1201') or (($var4_resultof_cast = 'MT2101') or (($var4_resultof_cast = 'MT2201') or (($var4_resultof_cast = 'MT3101') or (($var4_resultof_cast = 'MT3102') or (($var4_resultof_cast = 'MT3201') or (($var4_resultof_cast = 'MT3202') or (($var4_resultof_cast = 'MT4101') or (($var4_resultof_cast = 'MT4201') or (($var4_resultof_cast = 'MT5101') or (($var4_resultof_cast = 'MT5102') or (($var4_resultof_cast = 'MT5201') or (($var4_resultof_cast = 'MT5202') or (($var4_resultof_cast = 'MT6101') or (($var4_resultof_cast = 'MT6102') or (($var4_resultof_cast = 'MT6201') or (($var4_resultof_cast = 'MT6202') or (($var4_resultof_cast = 'MT7101') or (($var4_resultof_cast = 'MT8101') or (($var4_resultof_cast = 'MT8102') or (($var4_resultof_cast = 'MT8103') or (($var4_resultof_cast = 'MT8104') or (($var4_resultof_cast = 'MT8201') or (($var4_resultof_cast = 'MT8202') or (($var4_resultof_cast = 'MT8203') or (($var4_resultof_cast = 'MT8204') or (($var4_resultof_cast = 'MTECEX') or ($var4_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
									<i_e_flag>
										<xsl:choose>
											<xsl:when test="string((string($var6_resultof_equal) != 'false')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT1201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT2101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT2201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT3202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT4101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT4201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT5202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT6202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT7101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8103')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8104')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8203')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MT8204')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var4_resultof_cast = 'MTECEX')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:if test="string(($var4_resultof_cast = 'MTECIM')) != 'false'">
													<xsl:value-of select="'I'"/>
												</xsl:if>
											</xsl:otherwise>
										</xsl:choose>
									</i_e_flag>
								</xsl:if>
								<conta_id>
									<xsl:value-of select="string(ns0:EquipmentIdentification/ns0:ID)"/>
								</conta_id>
								<customs_code>
									<xsl:value-of select="string($var2_Declaration/ns0:DeclarationOfficeID)"/>
								</customs_code>
							</conta>
						</xsl:for-each>
					</contas>
					<xsl:for-each select="$var2_Declaration/ns0:AdditionalInformation">
						<ChangeReasons>
							<ChangeReason>
								<MSG_ID>
									<xsl:value-of select="$var8_resultof_cast"/>
								</MSG_ID>
								<MANIFEST_ID>
									<xsl:choose>
										<xsl:when test="string((string($var13_val) = '2')) != 'false'">
											<xsl:value-of select="concat(concat($var11_resultof_cast, '_'), $var12_resultof_cast)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string($var7_JourneyID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</MANIFEST_ID>
								<TRANSPORT_ID>
									<xsl:value-of select="$var11_resultof_cast"/>
								</TRANSPORT_ID>
								<VOYAGE_NO>
									<xsl:value-of select="$var12_resultof_cast"/>
								</VOYAGE_NO>
								<xsl:for-each select="$var2_Declaration/ns0:AdditionalInformation/ns0:Reason">
									<CHANGE_REASON>
										<xsl:value-of select="string(.)"/>
									</CHANGE_REASON>
								</xsl:for-each>
								<xsl:for-each select="$var2_Declaration/ns0:AdditionalInformation/ns0:ContactName">
									<CHANGE_PERSON>
										<xsl:value-of select="string(.)"/>
									</CHANGE_PERSON>
								</xsl:for-each>
								<xsl:for-each select="$var2_Declaration/ns0:AdditionalInformation/ns0:ContactTel">
									<CHANGE_TEL>
										<xsl:value-of select="string(.)"/>
									</CHANGE_TEL>
								</xsl:for-each>
							</ChangeReason>
						</ChangeReasons>
					</xsl:for-each>
				</content>
			</xsl:for-each>
		</Manifest>
	</xsl:template>
</xsl:stylesheet>
