<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2011r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:Declaration:datamodel:standard:CN:MT8103:1" exclude-result-prefixes="xs ns0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<Manifest>
			<xsl:for-each select="ns0:Manifest">
				<xsl:variable name="var1_Declaration" select="ns0:Declaration"/>
				<xsl:variable name="var2_Head" select="ns0:Head"/>
				<xsl:variable name="var3_BorderTransportMeans" select="$var1_Declaration/ns0:BorderTransportMeans"/>
				<xsl:variable name="var4_ChangeBorderTransportMeans" select="$var1_Declaration/ns0:ChangeBorderTransportMeans"/>
				<xsl:variable name="var5_resultof_cast" select="string($var2_Head/ns0:MessageType)"/>
				<xsl:variable name="var6_resultof_substring" select="substring($var5_resultof_cast, number('4'), number('1'))"/>
				<xsl:variable name="var7_resultof_equal" select="($var5_resultof_cast = 'MT1101')"/>
				<xsl:variable name="var8_JourneyID" select="$var3_BorderTransportMeans/ns0:JourneyID"/>
				<xsl:variable name="var9_ID" select="$var4_ChangeBorderTransportMeans/ns0:ID"/>
				<xsl:variable name="var10_resultof_cast" select="string($var2_Head/ns0:SenderID)"/>
				<xsl:variable name="var11_resultof_cast" select="string($var2_Head/ns0:ReceiverID)"/>
				<xsl:variable name="var12_resultof_cast" select="string($var2_Head/ns0:MessageID)"/>
				<xsl:variable name="var13_resultof_cast" select="string($var4_ChangeBorderTransportMeans/ns0:JourneyID)"/>
				<xsl:variable name="var14_resultof_cast" select="string($var3_BorderTransportMeans/ns0:ID)"/>
				<xsl:variable name="var15_resultof_cast" select="string($var8_JourneyID)"/>
				<xsl:variable name="var16_val">
					<xsl:choose>
						<xsl:when test="string(($var6_resultof_substring = '1')) != 'false'">
							<xsl:value-of select="'2'"/>
						</xsl:when>
						<xsl:when test="string(($var6_resultof_substring = '2')) != 'false'">
							<xsl:value-of select="'5'"/>
						</xsl:when>
						<xsl:otherwise>
							<xsl:value-of select="'2'"/>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:variable>
				<msg_info>
					<msg_id>
						<xsl:value-of select="$var12_resultof_cast"/>
					</msg_id>
					<function_code>
						<xsl:value-of select="string($var2_Head/ns0:FunctionCode)"/>
					</function_code>
					<msg_type>
						<xsl:value-of select="substring-after($var5_resultof_cast, 'MT')"/>
					</msg_type>
					<sender_id>
						<xsl:value-of select="$var10_resultof_cast"/>
					</sender_id>
					<receiver_id>
						<xsl:value-of select="$var11_resultof_cast"/>
					</receiver_id>
					<send_time>
						<xsl:value-of select="string($var2_Head/ns0:SendTime)"/>
					</send_time>
					<version>
						<xsl:value-of select="string($var2_Head/ns0:Version)"/>
					</version>
				</msg_info>
				<content>
					<transport>
						<manifest_id>
							<xsl:choose>
								<xsl:when test="string((string($var16_val) = '2')) != 'false'">
									<xsl:value-of select="concat(concat($var14_resultof_cast, '_'), $var15_resultof_cast)"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="string($var8_JourneyID)"/>
								</xsl:otherwise>
							</xsl:choose>
						</manifest_id>
						<message_id>
							<xsl:value-of select="$var12_resultof_cast"/>
						</message_id>
						<decl_traf_mode>
							<xsl:value-of select="string($var16_val)"/>
						</decl_traf_mode>
						<xsl:if test="string(((string($var7_resultof_equal) != 'false') or (($var5_resultof_cast = 'MT1201') or (($var5_resultof_cast = 'MT2101') or (($var5_resultof_cast = 'MT2201') or (($var5_resultof_cast = 'MT3101') or (($var5_resultof_cast = 'MT3102') or (($var5_resultof_cast = 'MT3201') or (($var5_resultof_cast = 'MT3202') or (($var5_resultof_cast = 'MT4101') or (($var5_resultof_cast = 'MT4201') or (($var5_resultof_cast = 'MT5101') or (($var5_resultof_cast = 'MT5102') or (($var5_resultof_cast = 'MT5201') or (($var5_resultof_cast = 'MT5202') or (($var5_resultof_cast = 'MT6101') or (($var5_resultof_cast = 'MT6102') or (($var5_resultof_cast = 'MT6201') or (($var5_resultof_cast = 'MT6202') or (($var5_resultof_cast = 'MT7101') or (($var5_resultof_cast = 'MT8101') or (($var5_resultof_cast = 'MT8102') or (($var5_resultof_cast = 'MT8103') or (($var5_resultof_cast = 'MT8104') or (($var5_resultof_cast = 'MT8201') or (($var5_resultof_cast = 'MT8202') or (($var5_resultof_cast = 'MT8203') or (($var5_resultof_cast = 'MT8204') or (($var5_resultof_cast = 'MTECEX') or ($var5_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
							<i_e_flag>
								<xsl:choose>
									<xsl:when test="string((string($var7_resultof_equal) != 'false')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT1201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT2101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT2201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT3101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT3102')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT3201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT3202')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT4101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT4201')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT5101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT5102')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT5201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT5202')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT6101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT6102')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT6201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT6202')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT7101')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8101')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8102')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8103')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8104')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8201')) != 'false'">
										<xsl:value-of select="'I'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8202')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8203')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MT8204')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:when test="string(($var5_resultof_cast = 'MTECEX')) != 'false'">
										<xsl:value-of select="'E'"/>
									</xsl:when>
									<xsl:otherwise>
										<xsl:if test="string(($var5_resultof_cast = 'MTECIM')) != 'false'">
											<xsl:value-of select="'I'"/>
										</xsl:if>
									</xsl:otherwise>
								</xsl:choose>
							</i_e_flag>
						</xsl:if>
						<voyage_no>
							<xsl:value-of select="$var15_resultof_cast"/>
						</voyage_no>
						<transport_id>
							<xsl:value-of select="$var14_resultof_cast"/>
						</transport_id>
						<change_manifest_id>
							<xsl:value-of select="concat(concat(string($var9_ID), '_'), $var13_resultof_cast)"/>
						</change_manifest_id>
						<change_voyage_no>
							<xsl:value-of select="$var13_resultof_cast"/>
						</change_voyage_no>
						<change_transport_id>
							<xsl:value-of select="string($var9_ID)"/>
						</change_transport_id>
						<xsl:for-each select="$var1_Declaration/ns0:AdditionalInformation">
							<remark>
								<xsl:value-of select="string(ns0:Content)"/>
							</remark>
						</xsl:for-each>
					</transport>
					<bills>
						<xsl:for-each select="$var1_Declaration/ns0:Consignment">
							<xsl:variable name="var17_AssociatedTransportDocument" select="ns0:AssociatedTransportDocument"/>
							<xsl:variable name="var18_ChangeConsignment" select="ns0:ChangeConsignment"/>
							<xsl:variable name="var19_resultof_exists" select="boolean($var17_AssociatedTransportDocument)"/>
							<xsl:variable name="var20_result">
								<xsl:for-each select="$var18_ChangeConsignment">
									<xsl:choose>
										<xsl:when test="string(boolean(ns0:AssociatedTransportDocument)) != 'false'">
											<xsl:value-of select="'1'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="''"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:for-each>
							</xsl:variable>
							<xsl:variable name="var21_resultof_any" select="boolean(string($var20_result))"/>
							<xsl:variable name="var22_result">
								<xsl:for-each select="$var18_ChangeConsignment">
									<xsl:choose>
										<xsl:when test="string(boolean(ns0:AssociatedTransportDocument)) != 'false'">
											<xsl:value-of select="'1'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="''"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:for-each>
							</xsl:variable>
							<xsl:variable name="var23_resultof_any" select="boolean(string($var22_result))"/>
							<bill>
								<manifest_id>
									<xsl:choose>
										<xsl:when test="string((string($var16_val) = '2')) != 'false'">
											<xsl:value-of select="concat(concat($var14_resultof_cast, '_'), $var15_resultof_cast)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string($var8_JourneyID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</manifest_id>
								<message_id>
									<xsl:value-of select="$var12_resultof_cast"/>
								</message_id>
								<change_manifest_id>
									<xsl:value-of select="concat(concat(string($var9_ID), '_'), $var13_resultof_cast)"/>
								</change_manifest_id>
								<receiver_code>
									<xsl:value-of select="$var11_resultof_cast"/>
								</receiver_code>
								<sender_code>
									<xsl:value-of select="$var10_resultof_cast"/>
								</sender_code>
								<bill_no>
									<xsl:choose>
										<xsl:when test="string((string($var19_resultof_exists) != 'false')) != 'false'">
											<xsl:for-each select="$var17_AssociatedTransportDocument">
												<xsl:value-of select="string(ns0:ID)"/>
											</xsl:for-each>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</bill_no>
								<bill_type>
									<xsl:choose>
										<xsl:when test="string((string($var19_resultof_exists) != 'false')) != 'false'">
											<xsl:value-of select="'1'"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'0'"/>
										</xsl:otherwise>
									</xsl:choose>
								</bill_type>
								<xsl:if test="string((string($var19_resultof_exists) != 'false')) != 'false'">
									<parent_bill_no>
										<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
									</parent_bill_no>
								</xsl:if>
								<xsl:variable name="var26_result">
									<xsl:choose>
										<xsl:when test="string((string((string($var23_resultof_any) != 'false')) != 'false')) != 'false'">
											<xsl:variable name="var24_result">
												<xsl:for-each select="$var18_ChangeConsignment">
													<xsl:choose>
														<xsl:when test="string(boolean(ns0:AssociatedTransportDocument)) != 'false'">
															<xsl:value-of select="'1'"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="''"/>
														</xsl:otherwise>
													</xsl:choose>
												</xsl:for-each>
											</xsl:variable>
											<xsl:value-of select="boolean(string($var24_result))"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="boolean($var18_ChangeConsignment)"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:variable>
								<xsl:if test="string((string($var26_result) != 'false')) != 'false'">
									<xsl:variable name="var25_val">
										<xsl:choose>
											<xsl:when test="string((string((string($var23_resultof_any) != 'false')) != 'false')) != 'false'">
												<xsl:for-each select="$var18_ChangeConsignment/ns0:AssociatedTransportDocument">
													<xsl:value-of select="string(ns0:ID)"/>
												</xsl:for-each>
											</xsl:when>
											<xsl:otherwise>
												<xsl:for-each select="$var18_ChangeConsignment">
													<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
												</xsl:for-each>
											</xsl:otherwise>
										</xsl:choose>
									</xsl:variable>
									<xsl:if test="string(not((string($var25_val) = ''))) != 'false'">
										<change_bill_no>
											<xsl:value-of select="string($var25_val)"/>
										</change_bill_no>
									</xsl:if>
								</xsl:if>
								<xsl:variable name="var29_result">
									<xsl:choose>
										<xsl:when test="string((string((string($var21_resultof_any) != 'false')) != 'false')) != 'false'">
											<xsl:variable name="var27_result">
												<xsl:for-each select="$var18_ChangeConsignment">
													<xsl:choose>
														<xsl:when test="string(boolean(ns0:AssociatedTransportDocument)) != 'false'">
															<xsl:value-of select="'1'"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="''"/>
														</xsl:otherwise>
													</xsl:choose>
												</xsl:for-each>
											</xsl:variable>
											<xsl:value-of select="boolean(string($var27_result))"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="boolean($var18_ChangeConsignment)"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:variable>
								<xsl:variable name="var31_result">
									<xsl:choose>
										<xsl:when test="string((string($var29_result) != 'false')) != 'false'">
											<xsl:variable name="var28_result">
												<xsl:choose>
													<xsl:when test="string((string((string($var21_resultof_any) != 'false')) != 'false')) != 'false'">
														<xsl:for-each select="$var18_ChangeConsignment/ns0:AssociatedTransportDocument">
															<xsl:value-of select="string(ns0:ID)"/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<xsl:for-each select="$var18_ChangeConsignment">
															<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
														</xsl:for-each>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:variable>
											<xsl:value-of select="($var28_result = '')"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="false()"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:variable>
								<xsl:if test="string(not((string($var31_result) != 'false'))) != 'false'">
									<xsl:variable name="var30_result">
										<xsl:for-each select="$var18_ChangeConsignment">
											<xsl:choose>
												<xsl:when test="string(boolean(ns0:AssociatedTransportDocument)) != 'false'">
													<xsl:value-of select="'1'"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="''"/>
												</xsl:otherwise>
											</xsl:choose>
										</xsl:for-each>
									</xsl:variable>
									<change_bill_type>
										<xsl:choose>
											<xsl:when test="string(boolean(string($var30_result))) != 'false'">
												<xsl:value-of select="'1'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="'0'"/>
											</xsl:otherwise>
										</xsl:choose>
									</change_bill_type>
								</xsl:if>
								<xsl:for-each select="$var18_ChangeConsignment">
									<xsl:variable name="var32_AssociatedTransportDocument" select="ns0:AssociatedTransportDocument"/>
									<xsl:if test="string(boolean($var32_AssociatedTransportDocument)) != 'false'">
										<xsl:variable name="var33_result">
											<xsl:for-each select="$var32_AssociatedTransportDocument">
												<xsl:value-of select="string(ns0:ID)"/>
											</xsl:for-each>
										</xsl:variable>
										<xsl:if test="string(not(($var33_result = ''))) != 'false'">
											<change_parent_bill_no>
												<xsl:value-of select="string(ns0:TransportContractDocument/ns0:ID)"/>
											</change_parent_bill_no>
										</xsl:if>
									</xsl:if>
								</xsl:for-each>
								<decl_traf_mode>
									<xsl:value-of select="string($var16_val)"/>
								</decl_traf_mode>
								<xsl:if test="string(((string($var7_resultof_equal) != 'false') or (($var5_resultof_cast = 'MT1201') or (($var5_resultof_cast = 'MT2101') or (($var5_resultof_cast = 'MT2201') or (($var5_resultof_cast = 'MT3101') or (($var5_resultof_cast = 'MT3102') or (($var5_resultof_cast = 'MT3201') or (($var5_resultof_cast = 'MT3202') or (($var5_resultof_cast = 'MT4101') or (($var5_resultof_cast = 'MT4201') or (($var5_resultof_cast = 'MT5101') or (($var5_resultof_cast = 'MT5102') or (($var5_resultof_cast = 'MT5201') or (($var5_resultof_cast = 'MT5202') or (($var5_resultof_cast = 'MT6101') or (($var5_resultof_cast = 'MT6102') or (($var5_resultof_cast = 'MT6201') or (($var5_resultof_cast = 'MT6202') or (($var5_resultof_cast = 'MT7101') or (($var5_resultof_cast = 'MT8101') or (($var5_resultof_cast = 'MT8102') or (($var5_resultof_cast = 'MT8103') or (($var5_resultof_cast = 'MT8104') or (($var5_resultof_cast = 'MT8201') or (($var5_resultof_cast = 'MT8202') or (($var5_resultof_cast = 'MT8203') or (($var5_resultof_cast = 'MT8204') or (($var5_resultof_cast = 'MTECEX') or ($var5_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
									<i_e_flag>
										<xsl:choose>
											<xsl:when test="string((string($var7_resultof_equal) != 'false')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT1201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT2101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT2201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT3101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT3102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT3201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT3202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT4101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT4201')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT5101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT5102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT5201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT5202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT6101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT6102')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT6201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT6202')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT7101')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8101')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8102')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8103')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8104')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8201')) != 'false'">
												<xsl:value-of select="'I'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8202')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8203')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MT8204')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:when test="string(($var5_resultof_cast = 'MTECEX')) != 'false'">
												<xsl:value-of select="'E'"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:if test="string(($var5_resultof_cast = 'MTECIM')) != 'false'">
													<xsl:value-of select="'I'"/>
												</xsl:if>
											</xsl:otherwise>
										</xsl:choose>
									</i_e_flag>
								</xsl:if>
								<goods_infos>
									<xsl:for-each select="$var18_ChangeConsignment">
										<xsl:variable name="var41_cur" select="."/>
										<xsl:for-each select="ns0:ConsignmentItem">
											<xsl:variable name="var34_EquipmentIdentification" select="ns0:EquipmentIdentification"/>
											<xsl:variable name="var35_AssociatedTransportDocument" select="$var41_cur/ns0:AssociatedTransportDocument"/>
											<xsl:variable name="var36_ConsignmentItemPackaging" select="ns0:ConsignmentItemPackaging"/>
											<xsl:variable name="var37_resultof_exists" select="boolean($var35_AssociatedTransportDocument)"/>
											<xsl:variable name="var38_Commodity" select="ns0:Commodity"/>
											<goods_info>
												<manifest_id>
													<xsl:choose>
														<xsl:when test="string((string($var16_val) = '2')) != 'false'">
															<xsl:value-of select="concat(concat($var14_resultof_cast, '_'), $var15_resultof_cast)"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="string($var8_JourneyID)"/>
														</xsl:otherwise>
													</xsl:choose>
												</manifest_id>
												<message_id>
													<xsl:value-of select="$var12_resultof_cast"/>
												</message_id>
												<change_manifest_id>
													<xsl:value-of select="concat(concat(string($var9_ID), '_'), $var13_resultof_cast)"/>
												</change_manifest_id>
												<change_bill_no>
													<xsl:choose>
														<xsl:when test="string((string($var37_resultof_exists) != 'false')) != 'false'">
															<xsl:for-each select="$var35_AssociatedTransportDocument">
																<xsl:value-of select="string(ns0:ID)"/>
															</xsl:for-each>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="string($var41_cur/ns0:TransportContractDocument/ns0:ID)"/>
														</xsl:otherwise>
													</xsl:choose>
												</change_bill_no>
												<change_bill_type>
													<xsl:choose>
														<xsl:when test="string((string($var37_resultof_exists) != 'false')) != 'false'">
															<xsl:value-of select="'1'"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="'0'"/>
														</xsl:otherwise>
													</xsl:choose>
												</change_bill_type>
												<xsl:if test="string((string($var37_resultof_exists) != 'false')) != 'false'">
													<change_parent_bill_no>
														<xsl:value-of select="string($var41_cur/ns0:TransportContractDocument/ns0:ID)"/>
													</change_parent_bill_no>
												</xsl:if>
												<decl_traf_mode>
													<xsl:value-of select="string($var16_val)"/>
												</decl_traf_mode>
												<xsl:if test="string(((string($var7_resultof_equal) != 'false') or (($var5_resultof_cast = 'MT1201') or (($var5_resultof_cast = 'MT2101') or (($var5_resultof_cast = 'MT2201') or (($var5_resultof_cast = 'MT3101') or (($var5_resultof_cast = 'MT3102') or (($var5_resultof_cast = 'MT3201') or (($var5_resultof_cast = 'MT3202') or (($var5_resultof_cast = 'MT4101') or (($var5_resultof_cast = 'MT4201') or (($var5_resultof_cast = 'MT5101') or (($var5_resultof_cast = 'MT5102') or (($var5_resultof_cast = 'MT5201') or (($var5_resultof_cast = 'MT5202') or (($var5_resultof_cast = 'MT6101') or (($var5_resultof_cast = 'MT6102') or (($var5_resultof_cast = 'MT6201') or (($var5_resultof_cast = 'MT6202') or (($var5_resultof_cast = 'MT7101') or (($var5_resultof_cast = 'MT8101') or (($var5_resultof_cast = 'MT8102') or (($var5_resultof_cast = 'MT8103') or (($var5_resultof_cast = 'MT8104') or (($var5_resultof_cast = 'MT8201') or (($var5_resultof_cast = 'MT8202') or (($var5_resultof_cast = 'MT8203') or (($var5_resultof_cast = 'MT8204') or (($var5_resultof_cast = 'MTECEX') or ($var5_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
													<i_e_flag>
														<xsl:choose>
															<xsl:when test="string((string($var7_resultof_equal) != 'false')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT1201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT2101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT2201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3102')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3202')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT4101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT4201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5102')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5202')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6102')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6202')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT7101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8102')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8103')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8104')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8202')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8203')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8204')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MTECEX')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:otherwise>
																<xsl:if test="string(($var5_resultof_cast = 'MTECIM')) != 'false'">
																	<xsl:value-of select="'I'"/>
																</xsl:if>
															</xsl:otherwise>
														</xsl:choose>
													</i_e_flag>
												</xsl:if>
												<g_no>
													<xsl:value-of select="string(ns0:SequenceNumeric)"/>
												</g_no>
												<pack_no>
													<xsl:value-of select="string(number(string($var36_ConsignmentItemPackaging/ns0:QuantityQuantity)))"/>
												</pack_no>
												<wrap_type>
													<xsl:value-of select="string($var36_ConsignmentItemPackaging/ns0:TypeCode)"/>
												</wrap_type>
												<xsl:for-each select="$var36_ConsignmentItemPackaging/ns0:MarksNumbers">
													<mark_contr>
														<xsl:value-of select="string(.)"/>
													</mark_contr>
												</xsl:for-each>
												<xsl:for-each select="$var38_Commodity/ns0:UNDGCode">
													<danger_code>
														<xsl:value-of select="string(.)"/>
													</danger_code>
												</xsl:for-each>
												<xsl:for-each select="$var38_Commodity/ns0:TariffClassificationCode">
													<code_ts>
														<xsl:value-of select="string(.)"/>
													</code_ts>
												</xsl:for-each>
												<goods_memo>
													<xsl:value-of select="string($var38_Commodity/ns0:CargoDescription)"/>
												</goods_memo>
												<xsl:for-each select="ns0:AdditionalInformation">
													<goods_details>
														<xsl:value-of select="string(ns0:Content)"/>
													</goods_details>
												</xsl:for-each>
												<gross_wt>
													<xsl:value-of select="string(number(string(ns0:GoodsMeasure/ns0:GrossMassMeasure)))"/>
												</gross_wt>
												<weight_unit>KG</weight_unit>
												<xsl:for-each select="ns0:CustomsProcedure">
													<service_code>
														<xsl:value-of select="string(ns0:CurrentCode)"/>
													</service_code>
												</xsl:for-each>
												<xsl:for-each select="ns0:UCR">
													<ucr>
														<xsl:value-of select="string(ns0:ID)"/>
													</ucr>
												</xsl:for-each>
												<xsl:for-each select="ns0:Origin">
													<origin_country>
														<xsl:value-of select="string(ns0:OriginCountryCode)"/>
													</origin_country>
												</xsl:for-each>
												<xsl:choose>
													<xsl:when test="string(boolean($var34_EquipmentIdentification)) != 'false'">
														<xsl:for-each select="$var34_EquipmentIdentification[not((string(string-length(substring(concat(string(ns0:ID), ';'), '1', (string-length(concat(string(ns0:ID), ';')) - '1')))) = '0'))]">
															<conta_id>
																<xsl:value-of select="substring(concat(string(ns0:ID), ';'), '1', (string-length(concat(string(ns0:ID), ';')) - '1'))"/>
															</conta_id>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<xsl:variable name="var39_resultof_first" select="';'"/>
														<xsl:variable name="var40_resultof_substring" select="substring($var39_resultof_first, '1', (string-length($var39_resultof_first) - '1'))"/>
														<xsl:if test="string(not((string(string-length($var40_resultof_substring)) = '0'))) != 'false'">
															<conta_id>
																<xsl:value-of select="$var40_resultof_substring"/>
															</conta_id>
														</xsl:if>
													</xsl:otherwise>
												</xsl:choose>
											</goods_info>
										</xsl:for-each>
									</xsl:for-each>
								</goods_infos>
								<xsl:for-each select="$var18_ChangeConsignment">
									<xsl:variable name="var48_cur" select="."/>
									<xsl:for-each select="ns0:TransportEquipment">
										<xsl:variable name="var42_SealID" select="ns0:SealID"/>
										<xsl:variable name="var43_AssociatedTransportDocument" select="$var48_cur/ns0:AssociatedTransportDocument"/>
										<xsl:variable name="var44_resultof_exists" select="boolean($var43_AssociatedTransportDocument)"/>
										<contas>
											<conta>
												<manifest_id>
													<xsl:choose>
														<xsl:when test="string((string($var16_val) = '2')) != 'false'">
															<xsl:value-of select="concat(concat($var14_resultof_cast, '_'), $var15_resultof_cast)"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="string($var8_JourneyID)"/>
														</xsl:otherwise>
													</xsl:choose>
												</manifest_id>
												<message_id>
													<xsl:value-of select="$var12_resultof_cast"/>
												</message_id>
												<change_manifest_id>
													<xsl:value-of select="concat(concat(string($var9_ID), '_'), $var13_resultof_cast)"/>
												</change_manifest_id>
												<change_bill_no>
													<xsl:choose>
														<xsl:when test="string((string($var44_resultof_exists) != 'false')) != 'false'">
															<xsl:for-each select="$var43_AssociatedTransportDocument">
																<xsl:value-of select="string(ns0:ID)"/>
															</xsl:for-each>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="string($var48_cur/ns0:TransportContractDocument/ns0:ID)"/>
														</xsl:otherwise>
													</xsl:choose>
												</change_bill_no>
												<change_bill_type>
													<xsl:choose>
														<xsl:when test="string((string($var44_resultof_exists) != 'false')) != 'false'">
															<xsl:value-of select="'1'"/>
														</xsl:when>
														<xsl:otherwise>
															<xsl:value-of select="'0'"/>
														</xsl:otherwise>
													</xsl:choose>
												</change_bill_type>
												<xsl:if test="string((string($var44_resultof_exists) != 'false')) != 'false'">
													<change_parent_bill_no>
														<xsl:value-of select="string($var48_cur/ns0:TransportContractDocument/ns0:ID)"/>
													</change_parent_bill_no>
												</xsl:if>
												<decl_traf_mode>
													<xsl:value-of select="string($var16_val)"/>
												</decl_traf_mode>
												<xsl:if test="string(((string($var7_resultof_equal) != 'false') or (($var5_resultof_cast = 'MT1201') or (($var5_resultof_cast = 'MT2101') or (($var5_resultof_cast = 'MT2201') or (($var5_resultof_cast = 'MT3101') or (($var5_resultof_cast = 'MT3102') or (($var5_resultof_cast = 'MT3201') or (($var5_resultof_cast = 'MT3202') or (($var5_resultof_cast = 'MT4101') or (($var5_resultof_cast = 'MT4201') or (($var5_resultof_cast = 'MT5101') or (($var5_resultof_cast = 'MT5102') or (($var5_resultof_cast = 'MT5201') or (($var5_resultof_cast = 'MT5202') or (($var5_resultof_cast = 'MT6101') or (($var5_resultof_cast = 'MT6102') or (($var5_resultof_cast = 'MT6201') or (($var5_resultof_cast = 'MT6202') or (($var5_resultof_cast = 'MT7101') or (($var5_resultof_cast = 'MT8101') or (($var5_resultof_cast = 'MT8102') or (($var5_resultof_cast = 'MT8103') or (($var5_resultof_cast = 'MT8104') or (($var5_resultof_cast = 'MT8201') or (($var5_resultof_cast = 'MT8202') or (($var5_resultof_cast = 'MT8203') or (($var5_resultof_cast = 'MT8204') or (($var5_resultof_cast = 'MTECEX') or ($var5_resultof_cast = 'MTECIM')))))))))))))))))))))))))))))) != 'false'">
													<i_e_flag>
														<xsl:choose>
															<xsl:when test="string((string($var7_resultof_equal) != 'false')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT1201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT2101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT2201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3102')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT3202')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT4101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT4201')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5102')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT5202')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6102')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT6202')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT7101')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8101')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8102')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8103')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8104')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8201')) != 'false'">
																<xsl:value-of select="'I'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8202')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8203')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MT8204')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:when test="string(($var5_resultof_cast = 'MTECEX')) != 'false'">
																<xsl:value-of select="'E'"/>
															</xsl:when>
															<xsl:otherwise>
																<xsl:if test="string(($var5_resultof_cast = 'MTECIM')) != 'false'">
																	<xsl:value-of select="'I'"/>
																</xsl:if>
															</xsl:otherwise>
														</xsl:choose>
													</i_e_flag>
												</xsl:if>
												<conta_id>
													<xsl:value-of select="string(ns0:EquipmentIdentification/ns0:ID)"/>
												</conta_id>
												<conta_type>
													<xsl:value-of select="string(ns0:CharacteristicCode)"/>
												</conta_type>
												<xsl:for-each select="ns0:SupplierPartyTypeCode">
													<conta_sour>
														<xsl:value-of select="string(.)"/>
													</conta_sour>
												</xsl:for-each>
												<empty_conta_mark>
													<xsl:value-of select="string(ns0:FullnessCode)"/>
												</empty_conta_mark>
												<xsl:variable name="var45_result">
													<xsl:for-each select="$var42_SealID">
														<xsl:choose>
															<xsl:when test="string(boolean(@AgencyCode)) != 'false'">
																<xsl:value-of select="'1'"/>
															</xsl:when>
															<xsl:otherwise>
																<xsl:value-of select="''"/>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:for-each>
												</xsl:variable>
												<xsl:choose>
													<xsl:when test="string(boolean(string($var45_result))) != 'false'">
														<xsl:for-each select="$var42_SealID[boolean(@AgencyCode)][not((string(string-length(substring(concat(concat(concat(string(.), '/'), string(@AgencyCode)), ';'), '1', (string-length(concat(concat(concat(string(.), '/'), string(@AgencyCode)), ';')) - '1')))) = '0'))]">
															<seal_id>
																<xsl:value-of select="substring(concat(concat(concat(string(.), '/'), string(@AgencyCode)), ';'), '1', (string-length(concat(concat(concat(string(.), '/'), string(@AgencyCode)), ';')) - '1'))"/>
															</seal_id>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<xsl:variable name="var46_resultof_first" select="';'"/>
														<xsl:variable name="var47_resultof_substring" select="substring($var46_resultof_first, '1', (string-length($var46_resultof_first) - '1'))"/>
														<xsl:if test="string(not((string(string-length($var47_resultof_substring)) = '0'))) != 'false'">
															<seal_id>
																<xsl:value-of select="$var47_resultof_substring"/>
															</seal_id>
														</xsl:if>
													</xsl:otherwise>
												</xsl:choose>
											</conta>
										</contas>
									</xsl:for-each>
								</xsl:for-each>
							</bill>
						</xsl:for-each>
					</bills>
					<xsl:for-each select="$var1_Declaration/ns0:AdditionalInformation">
						<ChangeReasons>
							<ChangeReason>
								<MSG_ID>
									<xsl:value-of select="$var12_resultof_cast"/>
								</MSG_ID>
								<MANIFEST_ID>
									<xsl:choose>
										<xsl:when test="string((string($var16_val) = '2')) != 'false'">
											<xsl:value-of select="concat(concat($var14_resultof_cast, '_'), $var15_resultof_cast)"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="string($var8_JourneyID)"/>
										</xsl:otherwise>
									</xsl:choose>
								</MANIFEST_ID>
								<TRANSPORT_ID>
									<xsl:value-of select="$var14_resultof_cast"/>
								</TRANSPORT_ID>
								<VOYAGE_NO>
									<xsl:value-of select="$var15_resultof_cast"/>
								</VOYAGE_NO>
								<xsl:for-each select="$var1_Declaration/ns0:AdditionalInformation/ns0:Reason">
									<CHANGE_REASON>
										<xsl:value-of select="string(.)"/>
									</CHANGE_REASON>
								</xsl:for-each>
								<xsl:for-each select="$var1_Declaration/ns0:AdditionalInformation/ns0:ContactName">
									<CHANGE_PERSON>
										<xsl:value-of select="string(.)"/>
									</CHANGE_PERSON>
								</xsl:for-each>
								<xsl:for-each select="$var1_Declaration/ns0:AdditionalInformation/ns0:ContactTel">
									<CHANGE_TEL>
										<xsl:value-of select="string(.)"/>
									</CHANGE_TEL>
								</xsl:for-each>
							</ChangeReason>
						</ChangeReasons>
					</xsl:for-each>
				</content>
			</xsl:for-each>
		</Manifest>
	</xsl:template>
</xsl:stylesheet>
